import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideMenu from "../components/admin/sideMenu";
import Header from "../components/admin/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex">
          <SideMenu />
          <div className="grow">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
